server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:MesVortex/youba_config.git
          default-label: main
          search-paths:
            - config-files

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/