server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MesVortex/youba_config.git
          default-label: main
          search-paths:
            - config-files